name: Stale Issues & PRs
on:
  schedule:
    - cron: "0/1 * * * *"

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
        - name: Cron Job
          run: echo I am executing per minutes change
